import { useState } from 'react';
import JobCard from './JobCard';
export default function JobListings({ jobs, applications, onApply }) {
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('All Categories');
  // filter() combines the title search and category dropdown in real time.
  const filtered = jobs.filter((job) => job.title.toLowerCase().includes(search.toLowerCase()) && (category === 'All Categories' || job.category === category));
  return <section id="jobs" className="py-5 bg-light"><div className="container"><div className="section-heading text-center mb-4"><span className="text-primary fw-semibold">FIND YOUR FIT</span><h2 className="mt-2">Explore open opportunities</h2><p className="text-secondary">A role with room to grow could be right around the corner.</p></div><div className="filter-bar card border-0 shadow-sm mb-4"><div className="card-body p-3"><div className="row g-2"><div className="col-md"><div className="input-group"><span className="input-group-text bg-white border-end-0"><i className="bi bi-search" /></span><input className="form-control border-start-0" placeholder="Search jobs by title..." value={search} onChange={(e) => setSearch(e.target.value)} /></div></div><div className="col-md-4"><select className="form-select" value={category} onChange={(e) => setCategory(e.target.value)}>{['All Categories', 'IT', 'HR', 'Marketing', 'Finance', 'Design'].map((item) => <option key={item}>{item}</option>)}</select></div></div></div></div><p className="text-secondary small mb-3">Showing <strong>{filtered.length}</strong> {filtered.length === 1 ? 'opportunity' : 'opportunities'}</p><div className="row g-4">{filtered.map((job) => <div className="col-md-6 col-xl-4" key={job.id}><JobCard job={job} applied={applications.some((application) => application.id === job.id)} onApply={onApply} /></div>)}</div>{!filtered.length && <div className="text-center py-5"><i className="bi bi-search fs-1 text-secondary" /><h3 className="h5 mt-3">No matching jobs found</h3><p className="text-secondary">Try a different job title or category.</p></div>}</div></section>;
}
